### ISSUE TITLE
Just a test for the template...

### ISSUE THREAD

**Issue by remotevase** [SWNetworkDevelopers/PHPStudio#2]
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for error messages.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable speaking in English

--------------------

Issue Description Here

Optional Info Here

**Comment by remotevase** [comment]
Oops! Few more changes

**Comment by Taki21** [comment]
xD
